Add Korean translation.
nanotee/nvim-lua-guide pull request #114
Opened 2022-08-16 15:44 UTC by krapjost

2022-08-18 04:29 UTC, jcha0713 commented
Hi, I came here to participate in translation and saw this. Do you mind if I go over and review your translation before it gets merged?

2022-08-18 06:30 UTC, krapjost commented
> Hi, I came here to participate in translation and saw this. Do you mind if I go over and review your translation before it gets merged?

sure!

2022-08-19 01:10 UTC, jcha0713 requested changes
The overall quality of translation is very good. Sorry to make you go over this long document all again. Mostly, the suggestions are trivial and some are based on my personal preference, but there are some lines that definitely need to be changed for the sake of clarity. 

Before I end this long review, I want to highlight that it's important to be consistent throughout the page. For example, you used the word 빌트인(builtin) a lot in this document, and while I personally suggest to change it to the corresponding Korean word (내장), I think it's okay as long as you can keep consistency. This also applies to other words like linter, language server, and Neovim.

Lastly, I want to let you know that I did not make any changes for word spacing(띄어쓰기) since it would too much work for both of us; I recommend to use the word spacing checker or 맞춤법검사기 as the last step.

2022-08-21 09:38 UTC, krapjost commented on README.md
> +# Neovim에서 Lua 사용 시작하기
지금 여기서 바로 수정하면 제가 포크한 리포가 아니라 본 리포에 적용되는 것 같은데 제 리포지터리에서 수정하겠습니다!

2022-08-21 09:48 UTC, krapjost commented on README.md
> +자바스크립트같은 스트립팅 언어에 대한 경험이 있다면 정말 쉽게 배울 수 있습니다. 그렇지 않더라도요.
띄워쓰기 수정하겠습니다!
스크립트로 수정하겠습니다!

2022-08-21 09:51 UTC, krapjost commented on README.md
> +알림: `init.lua` 파일을 사용하는 것은 물론 _완전히_ 선택 가능합니다. `init.vim`을 사용해도 상관 없으며 여전히 유효한 설정입니다. vim의 기능들 중 몇몇은 아직 루아로 접근할 수 없다는 것도 기억하면 좋습니다.
네 선택사항입니다고 바꾸었습니다!

2022-08-21 09:53 UTC, krapjost commented on README.md
> +`init.lua` 파일을 포함하고 있는 폴더는 파일 이름을 지정하지 않아도 바로 불러올 수 있습니다.
명시라는 단어가 더 의미가 명확하네요! 변경하겠습니다!

2022-08-21 09:55 UTC, krapjost commented on README.md
> +그래서 당신의 설정 파일이나 플러그인들의 namespace를 최상위 폴더와 같이 관리하는 것도 좋은 아이디어일 수 있습니다. 다음과 같이요:
넵 이름공간으로 바꾸었습니다.

2022-08-21 10:02 UTC, krapjost commented on README.md
> +### 루아 파일 가져오기 (Sourcing Lua files)
:[range]so[urce] [file]	Runs |Ex| commands or Lua code (".lua" files) from [file]
파일에서 가져온 루아 코드 혹은 커맨드를 실행하는 것이라고 적혀있는데 정확하게 번역하자면 '가져와서 실행하기'가 되어야 할 것 같아요. ㅎㅎ그래서 옆에 그냥 원문을 남겨두었습니다.

2022-08-21 10:11 UTC, krapjost commented on README.md
> +Neovim은 루아 파일을 가져오기 위해 다음 3개의 실행 명령어들을 제공합니다.
Ex commands가 명사로 사용된 것 아닐까요? 말 그대로 콜론으로 들어간 명령행에서 입력하는 "실행 명령어"들이요.

2022-08-21 10:12 UTC, krapjost commented on README.md
> +#### 루아 파일 가져오기 (sourcing) vs require() 호출하기:
sourcing 뜻 자체가 가져오기라는 뜻이라서 실행하기는 너무 의역인 것 같아요...!

2022-08-21 10:15 UTC, krapjost commented on README.md
> +" 알림 루아의 테이블은 1부터 인덱싱 되지만 빔의 리스트는 0부터입니다.
음 이거는 어떤 의미인지 잘 모르겠습니다.

2022-08-21 10:16 UTC, krapjost commented on README.md
> +" Dict-like 테이블은 빔의 딕셔너리로 변환됩니다.
네 그게 더 이해하기 쉬울 것 같네요!

2022-08-21 10:17 UTC, krapjost commented on README.md
> +" 루아 함수들을 빔스크립트에서 alias를 만들어 사용할 수도 있습니다.
네 동의합니다.

2022-08-21 10:19 UTC, krapjost commented on README.md
> +" 생략된 괄호와 작은 따옴표를 사용하여 루아 모듈에서 함수를 호출하기:
그게 훨씬 낫네요!. 감사합니다.

2022-08-21 10:23 UTC, krapjost commented on README.md
> +#### 경고
경고와 주의사항 사이에 큰 의미 차이가 있는 것 같진 않은데 Caveat이 좀 약한 의미에서 쓰이나요?

2022-08-21 10:25 UTC, krapjost commented on README.md
> +이 함수는 빔스크립트 표현식 문자열에서 값을 리턴합니다. 빔스크립트의 데이터 타입들은 자동적으로 루아 타입으로 변환됩니다.
네 확실히 더 읽기 편해지네요!

2022-08-21 10:25 UTC, krapjost commented on README.md
> +이 함수는 빔스크립트 코드 조각을 평가합니다. 실행할 소스 코드 문자열과 코드의 결과가 리턴할지 지정하는 boolean 값을 인자로 받습니다. (결과값을 변수에 할당하는 것도 가능합니다).
변경했습니다.

2022-08-21 10:26 UTC, krapjost commented on README.md
> +빔스크립트로 씌여진 다음과 같은 키 매핑이 있습니다:
확인했습니다!

2022-08-21 10:27 UTC, krapjost commented on README.md
> +미리 정의된 빔 변수들을 제외하고는 삭제할 수도 있습니다(빔스크립트에서는 `:unlet` 커맨드와 같습니다). 로컬 변수 (`l:`), 스크립트 변수 (`s:`),
이것도 수정했습니다!

2022-08-21 10:28 UTC, krapjost commented on README.md
> +함수 인자 (`a:`)는  조작할 수 없습니다. 이것들은 빔스크립트의 문맥에서만 의미가 있고, 루아에서는 루아의 스코핑 규칙이 있습니다.
네 이것도 변경해주신게 더 명확하네요!

2022-08-21 10:29 UTC, krapjost commented on README.md
> +`vim.api.nvim_get_keymap()`은 모드의 짧은 이름 문자열(위의 테이블)을 인수로 받고 해당 모드에 포함된 매핑들을 테이블로 반환합니다.
네!

2022-08-21 10:31 UTC, krapjost commented on README.md
> +-- 모듈을 require 할 때 드는 시작 비용을 피하기 위해서 function으로 감싸 매핑을 부를 때 (layzily) require 할 수 있게 합니다:
'avoid the startup cost' 이면 lazy로딩 시 시작 비용을 피할 수 있다는 의미 같은데 원문 그대로 번역하면 '줄일 수 있다' 보다 '피할 수 있다'가 정확하지 않을까요?

2022-08-21 10:34 UTC, krapjost commented on README.md
> +-- 모듈을 require 할 때 드는 시작 비용을 피하기 위해서 function으로 감싸 매핑을 부를 때 (layzily) require 할 수 있게 합니다:
모듈을 불러올 때 드는 시작 비용을 피하기 위해 require를 function으로 감싸 매핑을 호출할 때 실행되도록 할 수 있습니다:
이렇게 수정하겠습니다!

2022-08-21 10:43 UTC, krapjost commented on README.md
> +[rafcamlet/coc-nvim-lua](https://github.com/rafcamlet/coc-nvim-lua/)는 [coc.nvim](https://github.com/neoclide/coc.nvim/)을 위한 자동완성 소스입니다.
coc 플러그인을 위한 자동완성 소스인 것 맞는데 coc가 제공하는 기능이 stdlib에 완성 항목을 제공하는 기능인 것 같습니다. Neovim stdlib에 자동완성 항목들을 제공합니다. 라고 추가하겠습니다.

2022-08-21 10:43 UTC, krapjost commented on README.md
> +## 잡다
그 외가 더 낫네요!

2022-08-21 10:45 UTC, krapjost commented on README.md
> +루아 프로젝트에 diagnostics와 autocompletion를 적용하기 위해 린터나 랭귀지 서버를 사용한다면 네오빔 특정 세팅을 설정해줘야 합니다. 여기 유명한 도구들을 위한 추천하는 세팅이 몇 개 있습니다:
네 그렇게 변경했습니다.

2022-08-21 10:46 UTC, krapjost commented on README.md
> +클라이언트 동작은 "lap-handlers"를 사용해 구성할 수 있습니다. 자세한 정보:
감사합니다!

2022-08-21 10:48 UTC, krapjost commented on README.md
> +[네오빔에서 first-class 언어](https://github.com/neovim/neovim/wiki/FAQ#why-embed-lua-instead-of-x)로서 [통합된 루아](https://www.youtube.com/watch?v=IP3J56sKtn0)는 킬러 피쳐들 중 하나로 자리잡고 있습니다.
네 적용했습니다!

2022-08-21 10:54 UTC, krapjost commented on README.md
> +이 빔스크립트 빌트인 함수는 루아 표현식(expression) 문자열의 값을 도출하고 그 값을 리턴합니다. 루아의 데이터 타입들은 자동적으로 빔스크립트 타입들로 변환됩니다.
이건 제가 나중에 로컬에서 한 번에 변경하도록 하겠습니다. 감사합니다!

2022-08-23 03:27 UTC, jcha0713 reviewed
의견 고려해주셔서 감사합니다!

LGTM!

2022-11-08 06:19 UTC, flavono123 commented
@nanotee Why this is not merged yet?

2022-11-21 19:47 UTC, merged

2022-11-21 19:52 UTC, nanotee commented
Terribly sorry about the long wait. Thank you @krapjost for your translation and @jcha0713 for your review